name: Build Project
on: 
  push:
    branches: [ master ]

  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
   
      - name: Compile Prog
        run: |
          sudo apt-get install g++-10
          g++ -dumpversion
          g++ main.cpp -o launch.exe
          ls
          
      - name: Make exe
        uses: actions/upload-artifact@v2
        with:
          name: Result
          path: launch.exe
