name: Build Project
on: 
  push:
    branches: [ master ]

  workflow_dispatch:
 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
   
      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install g++-10
          g++ -dumpversion
          g++ main.cpp -o launch.exe
          ls
          
      - name: Make exe
        uses: actions/upload-artifact@v2
        with:
          name: Result
          path: launch.exe
