name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: check file
      id: check_file
      uses: andstor/file-existence-action@v1
      with:
        files: "test_bool.txt"
