name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
   
  workflow_dispatch:
   
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
    
      - name: Check files existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "test_travis.txt"
        
      - name: File exists
        if: steps.check_files.output.files_exists == 'true'
        run: echo Required files exist
