name: CI

on:
  push:
    branches: [ master ]
   
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
    
      - name: Check files existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "test_travis.txt"
        
      - name: File exists
        if: steps.check_files.output.files_exists == 'true'
        run: echo Required files exist
        
      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: output/
          destination-github-username: 'SirDotJ'
          destination-repository-name: 'pnu_test_project.io'
          user-email: 2020102045@pnu.edu.ru
          target-branch: master
